[package]
name = "net_tools"
version = "0.1.0"
edition = "2021"


[dependencies]

ipnet = "2.10.1"
tokio = { version = "1", features = ["full"] }
pnet = "0.35.0"
anyhow = "1.0.94"
rand = "0.9.0-beta.1"
config = "0.14.1"
serde = "1.0.215"